// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/code-analyze/02-first-screen":{"path":"code-analyze/02-first-screen","id":"docs/code-analyze/02-first-screen","parentId":"DocLayout"},"docs/code-analyze/01-prepare":{"path":"code-analyze/01-prepare","id":"docs/code-analyze/01-prepare","parentId":"DocLayout"},"docs/code-analyze/index":{"path":"code-analyze","id":"docs/code-analyze/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/linjiajian/Desktop/my/react-speedrun/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/linjiajian/Desktop/my/react-speedrun/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout__index" */'/Users/linjiajian/Desktop/my/react-speedrun/.dumi/theme/layouts/DocLayout/index.tsx')),
'docs/code-analyze/02-first-screen': React.lazy(() => import(/* webpackChunkName: "docs__code-analyze__02-first-screen.md" */'/Users/linjiajian/Desktop/my/react-speedrun/docs/code-analyze/02-first-screen.md')),
'docs/code-analyze/01-prepare': React.lazy(() => import(/* webpackChunkName: "docs__code-analyze__01-prepare.md" */'/Users/linjiajian/Desktop/my/react-speedrun/docs/code-analyze/01-prepare.md')),
'docs/code-analyze/index': React.lazy(() => import(/* webpackChunkName: "docs__code-analyze__index.md" */'/Users/linjiajian/Desktop/my/react-speedrun/docs/code-analyze/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/linjiajian/Desktop/my/react-speedrun/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/linjiajian/Desktop/my/react-speedrun/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
