// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/linjiajian/Desktop/my/react-speedrun/node_modules/dumi/theme-default/slots/HeaderExtra/index.js';
